"""cocotb integration testbench for <design_name> — golden model cross-check.
Generated by VeriFlow-CC.

Timing convention (IMPORTANT):
  cocotb + iverilog via VPI: after `await RisingEdge(dut.clk)`, cocotb reads
  values produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
  cocotb sees POST-NBA of posedge N-1 = PRE-NBA of posedge N.

  The golden model trace records the register state AFTER each posedge's NBA.
  The cocotb comparison loop reads each trace entry at the NEXT RisingEdge.

  Practical effect: the golden model records the NEW register values after each
  computation step. The comparison is aligned by DRIVE_PHASE_CYCLES offset.

  Registered outputs (ready, hash_valid, etc.) have a 1-cycle delay: they
  reflect the combinational _next signal from the PREVIOUS posedge's state.

Clock management (IMPORTANT):
  In cocotb v2.0+, background tasks (including Clock) are killed between tests.
  Each test MUST call ensure_clock() to start a fresh clock instance.
  Do NOT use a global _CLOCK_STARTED flag.

Two verification modes:
- test_layered: Golden model cycle-by-cycle output port comparison (algorithm designs)
- test_internal_signals: Per-cycle internal register comparison against golden model
- test_protocol: Protocol compliance checks (all designs)

Port configuration constants below are populated from spec.json by the codegen
stage. If codegen does not populate them, defaults are used and only
top-level port signals are checked.
"""

import os, sys
from pathlib import Path
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, Timer

CLK_PERIOD_NS = None  # codegen: MUST set FULL period from spec.timing.target_frequency_mhz
                      # (period_ns = 1000 / target_frequency_mhz). cocotb's Clock()
                      # takes the FULL period, NOT half-period.
RESET_CYCLE_SKIP = 1  # Golden cycle 0 is the reset state; comparison starts at cycle 1
TIMEOUT_CYCLES = 500
FAIL_COUNT = 0

# ─── Golden model import ────────────────────────────────────────────────
GOLDEN_AVAILABLE = False
GM_PATH = Path(__file__).parent.parent / "docs" / "golden_model.py"
if GM_PATH.exists():
    sys.path.insert(0, str(GM_PATH.parent))
    try:
        from golden_model import run as golden_run
        GOLDEN_AVAILABLE = True
    except ImportError as _e:
        import warnings
        warnings.warn(f"[GOLDEN] Import failed: {_e}. Per-cycle tests will be skipped.")

# ─── Port configuration ─────────────────────────────────────────────────
# Populated from spec.json by the codegen stage.
# Codegen MUST fill these in — they are NOT optional.
# If a port category is empty for this design, codegen sets it to {}.
INPUT_PORTS = {}          # {"port_name": width_bits, ...}
OUTPUT_PORTS = {}         # {"port_name": width_bits, ...}
VALID_OUTPUT_PORTS = []   # ["valid_out", ...] — output ports indicating valid data
HANDSHAKE_PORTS = {}      # {"valid_in": "ready_out"} — valid -> ack mapping
HOLD_UNTIL_ACK_PORTS = [] # ["valid_in", ...] — ports with hold_until_ack protocol

# DRIVE_PHASE_CYCLES: offset between golden model (software instantaneous) and RTL
# (post-NBA registered). Populated from spec.json timing_convention field:
#   spec.timing_convention.golden_to_rtl_offset_cycles
# Falls back to max(pipeline_delay_cycles) from module_connectivity timing_contract
# if timing_convention is not set (backward compat).
#
# Codegen MUST set this from spec.json. If codegen doesn't, the fallback below
# reads spec.json at import time to compute a reasonable default.
DRIVE_PHASE_CYCLES = 0    # codegen: set from spec.timing_convention.golden_to_rtl_offset_cycles

# Fallback: if codegen didn't set DRIVE_PHASE_CYCLES, try reading spec.json
if DRIVE_PHASE_CYCLES == 0:
    try:
        _spec_path = Path(__file__).parent.parent / "docs" / "spec.json"
        if _spec_path.exists():
            import json as _json
            _spec = _json.loads(_spec_path.read_text())
            _tc = _spec.get("timing_convention", {})
            _offset = _tc.get("golden_to_rtl_offset_cycles")
            if isinstance(_offset, int) and _offset > 0:
                DRIVE_PHASE_CYCLES = _offset
            else:
                # Fallback: max pipeline_delay_cycles across all modules
                _delays = []
                for _m in _spec.get("modules", []):
                    _d = _m.get("timing_contract", {}).get("pipeline_delay_cycles")
                    if isinstance(_d, (int, float)):
                        _delays.append(int(_d))
                if _delays:
                    DRIVE_PHASE_CYCLES = max(_delays)
    except Exception:
        pass


# ─── Clock management ───────────────────────────────────────────────────
# CRITICAL: In cocotb v2.0+, background tasks (including Clock) are killed
# between tests. Each test MUST call ensure_clock() to start a fresh clock.

async def ensure_clock(dut):
    """Start clock. Must be called at the start of every test."""
    assert CLK_PERIOD_NS is not None, (
        "CLK_PERIOD_NS not populated — codegen must set from spec.timing.target_frequency_mhz"
    )
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())
    await RisingEdge(dut.clk)


# ─── Helpers ────────────────────────────────────────────────────────────

async def reset_dut(dut):
    """Apply synchronous reset and wait for outputs to settle."""
    global FAIL_COUNT
    dut.rst.value = 1
    # Zero all input ports only (not outputs — outputs are driven by DUT)
    for name in INPUT_PORTS:
        try:
            sig = getattr(dut, name)
            if hasattr(sig, 'value') and hasattr(sig, 'setimmediatevalue'):
                sig.value = 0
        except Exception:
            pass
    # Also zero any valid input ports from HANDSHAKE_PORTS
    for valid_name in HANDSHAKE_PORTS:
        try:
            getattr(dut, valid_name).value = 0
        except Exception:
            pass
    await ClockCycles(dut.clk, 3)
    dut.rst.value = 0
    await RisingEdge(dut.clk)  # rst deassert sampled, outputs stable


def check(dut, expected, signal, test_name, cycle):
    """Raise AssertionError on mismatch. signal is a dut handle."""
    global FAIL_COUNT
    actual = int(signal.value)
    if expected != actual:
        FAIL_COUNT += 1
        width = len(signal)
        msg = (
            f"[FAIL] {test_name} cycle={cycle} {signal._name}: "
            f"expected=0x{expected:0{(width + 3) // 4}x} got=0x{actual:0{(width + 3) // 4}x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)


async def drive_inputs(dut, input_values, valid_name='valid_in',
                       ready_name='ready_out',
                       hold_data_cycles=None):
    """Wait for ready, then drive valid=1 with input values.

    Timing (POST-NBA):
    1. Wait for ready=1
    2. Drive ALL inputs simultaneously (valid + data)
    3. Wait ONE RisingEdge — DUT samples inputs at this posedge, NBA fires
    4. Deassert valid. For data inputs, hold for additional cycles based on
       pipeline_delay_cycles to ensure downstream modules have sampled.

    Args:
        dut: cocotb DUT handle
        input_values: dict mapping port names to integer values
        valid_name: name of the valid input port
        ready_name: name of the ready/ack output port
        hold_data_cycles: extra cycles to hold data after deasserting valid.
            Defaults to DRIVE_PHASE_CYCLES. If the control signal that triggers
            sampling has pipeline_delay_cycles=N, data must remain stable for
            N+1 cycles after valid is deasserted.
    """
    if hold_data_cycles is None:
        hold_data_cycles = DRIVE_PHASE_CYCLES

    # Wait for ready
    timeout = TIMEOUT_CYCLES
    ready_sig = getattr(dut, ready_name)
    while int(ready_sig.value) != 1 and timeout > 0:
        await RisingEdge(dut.clk)
        timeout -= 1
    assert timeout > 0, "Timeout waiting for ready before drive_inputs"

    # Drive all inputs at once
    for port_name, value in input_values.items():
        getattr(dut, port_name).value = value
    getattr(dut, valid_name).value = 1

    # Wait one rising edge — DUT samples inputs at this posedge
    await RisingEdge(dut.clk)

    # Deassert based on handshake protocol
    if valid_name in HOLD_UNTIL_ACK_PORTS:
        # hold_until_ack: keep valid high until DUT asserts ready
        pass  # caller is responsible for deasserting after ack
    else:
        # single_cycle / pulse: deassert valid immediately after sampling
        getattr(dut, valid_name).value = 0
        # Hold data for pipeline_delay_cycles so downstream consumers
        # (e.g., w_gen that sees load_en 2 cycles late) still see stable data.
        for _ in range(hold_data_cycles):
            await RisingEdge(dut.clk)
        for port_name in input_values:
            getattr(dut, port_name).value = 0


async def wait_valid(dut, valid_name='valid_out', max_cycles=200):
    """Poll for valid=1, return cycle count waited."""
    valid_sig = getattr(dut, valid_name)
    for i in range(max_cycles):
        await RisingEdge(dut.clk)
        if int(valid_sig.value) == 1:
            return i + 1
    return -1  # timeout


# ─── VCD capture ──────────────────────────────────────────────────────
# VCD is handled by cocotb_runner.py (waves=True) or the Makefile.
# No in-test action needed — the runner configures iverilog to dump VCD.


# ─── Tests ──────────────────────────────────────────────────────────────

@cocotb.test()
async def test_reset(dut):
    """Test 1: Reset behavior — outputs quiescent after reset."""
    global FAIL_COUNT
    FAIL_COUNT = 0  # reset per-test counter
    await ensure_clock(dut)
    await reset_dut(dut)

    # After reset: verify all output ports are 0
    reset_ok = True
    for port_name in OUTPUT_PORTS:
        try:
            sig = getattr(dut, port_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(f"[RESET] {port_name}={val} after reset, expected 0")
                reset_ok = False
        except AttributeError:
            dut._log.warning(f"[RESET] Port {port_name} not found in DUT")

    if reset_ok:
        dut._log.info("[PASS] reset behavior correct")


@cocotb.test()
async def test_protocol(dut):
    """Test 2: Protocol compliance — handshake and valid behavior.

    Checks that apply to ALL designs regardless of golden model availability:
    1. Reset clears all valid output ports
    2. hold_until_ack: valid stays high until ack received
    3. single_cycle: valid is high for exactly one cycle
    4. No stale valid after operation completes

    Note: Checks 2-4 require stimulus. Codegen adds design-specific
    protocol monitors. This test provides the framework.
    """
    global FAIL_COUNT
    await ensure_clock(dut)
    await reset_dut(dut)

    # Check 1: After reset, all valid output ports must be 0
    for valid_name in VALID_OUTPUT_PORTS:
        try:
            sig = getattr(dut, valid_name)
            val = int(sig.value)
            if val != 0:
                FAIL_COUNT += 1
                dut._log.error(
                    f"[PROTOCOL] {valid_name}={val} after reset, expected 0"
                )
        except AttributeError:
            pass  # port not found in DUT, skip

    # Check 2-4: Design-specific protocol monitors added by codegen
    # Example for hold_until_ack monitoring:
    #   prev_valid = 0
    #   for cycle in range(MAX_CYCLES):
    #       await RisingEdge(dut.clk)
    #       cur_valid = int(dut.valid_out.value)
    #       cur_ready = int(dut.ready_out.value)
    #       if prev_valid == 1 and cur_valid == 0 and cur_ready == 0:
    #           dut._log.error("[PROTOCOL] valid dropped before ready")
    #       prev_valid = cur_valid

    if FAIL_COUNT == 0:
        dut._log.info("[PASS] protocol compliance checks passed")


@cocotb.test()
async def test_layered(dut):
    """Test 3: Layered verification — golden model cycle-by-cycle comparison.

    For algorithm designs with a golden model:
    1. Drive input stimulus from golden model test vectors
    2. Compare DUT output signals against golden model per-cycle expected values
    3. Fail-fast on first mismatch: report cycle, signal, expected vs actual
    4. This quickly isolates WHERE the first computation error occurs

    Skipped if golden_model.py is not available (non-algorithm designs).
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_layered: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    # Get golden model expected values
    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_layered: golden model returned no data")
        return

    dut._log.info(f"[LAYERED] Comparing {len(expected_cycles)} cycles against golden model")

    # IMPORTANT: codegen MUST add drive_inputs() call here with golden model
    # test vectors before the comparison loop. Without driving inputs,
    # the DUT has no stimulus and all outputs will be initial values.
    #
    # Example (codegen fills in):
    #   test_vectors = golden_model.TEST_VECTORS
    #   for vec in test_vectors:
    #       await drive_inputs(dut, vec["inputs"], valid_name="valid_in",
    #                         ready_name="ready_out")
    #
    # If golden_model.py provides input data per cycle, drive it here.
    # If the design processes a single input block, drive once then wait.
    # <CODEGEN: drive_inputs() call here>

    # Stimulus guard: verify that at least one input port was driven to non-zero.
    # If drive_inputs() was never called, the DUT receives zero stimulus and
    # any comparison against golden model is meaningless.
    if INPUT_PORTS and all(int(getattr(dut, n).value) == 0 for n in INPUT_PORTS):
        raise AssertionError(
            "test_layered: no input stimulus detected — drive_inputs() was never called"
        )

    # Map golden trace signal names to DUT port names.
    # Golden model uses "_reg" suffix; DUT output ports don't.
    # Codegen populates this from spec.json port names.
    GOLDEN_TO_PORT = {}  # {"ready_reg": "ready", "hash_valid_reg": "hash_valid", ...}

    if not GOLDEN_TO_PORT:
        raise AssertionError(
            "test_layered: GOLDEN_TO_PORT is empty — codegen did not populate port mapping"
        )

    first_divergence = None
    cycles_checked = 0
    signals_compared = 0

    # Alignment derivation (avoid the double-offset bug from SM3 pipeline):
    #   drive_inputs() already advanced the DUT through 1 sample posedge plus
    #   DRIVE_PHASE_CYCLES "hold" posedges. After drive_inputs returns, the
    #   DUT register state corresponds to golden cycle 1 (= "after the first
    #   logical computation step"). DRIVE_PHASE_CYCLES is therefore consumed
    #   inside drive_inputs and MUST NOT be added to the golden-trace slice
    #   here as well — doing so caused (N-1)-cycle offsets in earlier runs.
    #
    # Slice rule: skip ONLY golden cycle 0 (reset state). Then compare
    # BEFORE advancing the clock, so iteration 0 reads DUT at the state left
    # by drive_inputs (= golden cycle 1), iteration 1 at golden cycle 2, etc.
    compare_cycles = expected_cycles[RESET_CYCLE_SKIP:]

    for cycle_idx, expected in enumerate(compare_cycles):
        # Compare each output signal against golden model — DUT state already
        # reflects this golden cycle, so do NOT await before comparing.
        for sig_name, expected_val in expected.items():
            # Map golden trace name to DUT port name
            dut_name = GOLDEN_TO_PORT.get(sig_name)
            if dut_name is None:
                continue  # not a mapped output port
            try:
                sig = getattr(dut, dut_name)
                actual_val = int(sig.value)
                signals_compared += 1
                if actual_val != expected_val:
                    first_divergence = {
                        "cycle": cycle_idx,
                        "signal": sig_name,
                        "expected": expected_val,
                        "actual": actual_val,
                    }
                    break
            except AttributeError:
                pass  # signal not accessible in DUT hierarchy, skip

        cycles_checked += 1

        if first_divergence:
            break

        # Advance DUT one cycle for the NEXT golden entry.
        await RisingEdge(dut.clk)

    # Report results
    if signals_compared == 0:
        raise AssertionError(
            "test_layered: ZERO signals were compared — GOLDEN_TO_PORT keys "
            "do not match any golden trace signal names"
        )
    if first_divergence:
        FAIL_COUNT += 1
        div = first_divergence
        msg = (
            f"[LAYERED] FIRST DIVERGENCE at cycle={div['cycle']} "
            f"signal={div['signal']}: "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[LAYERED] PASS — {cycles_checked} cycles matched golden model"
        )


@cocotb.test()
async def test_internal_signals(dut):
    """Test 4: Per-cycle internal signal comparison against golden model.

    This is the KEY verification test. It reads RTL internal registers
    via VPI (cocotb's dut.hierarchy.signal.value) and compares them
    against golden model trace on EVERY clock cycle.

    This test catches bugs that test_layered misses — test_layered only
    compares top-level output ports, missing internal register divergences.

    Timing semantics:
        After `await RisingEdge(dut.clk)`, cocotb + iverilog VPI reads values
        produced by the PREVIOUS posedge's NBA. Equivalently: at RisingEdge N,
        cocotb sees POST-NBA of posedge N-1.

        The golden model trace records POST-NBA state for each posedge.
        The comparison loop reads trace[N] at RisingEdge N, which shows the
        results of posedge N-1's computation.

        Registered outputs (ready, valid, etc.) have a 1-cycle delay from
        the FSM state that computes them — the golden model must track this.

        Alignment rule (single source of truth — do NOT add offsets elsewhere):
        DRIVE_PHASE_CYCLES is consumed entirely inside `drive_inputs()` via
        its `hold_data_cycles` parameter. When drive_inputs() returns, the
        DUT register state corresponds to golden cycle 1. The comparison
        loop therefore slices the trace as `expected_cycles[RESET_CYCLE_SKIP:]`
        (skip ONLY the reset state) and compares BEFORE the next await —
        do not re-add DRIVE_PHASE_CYCLES to this slice.

    Skipped if golden_model.py trace mode does not include internal signals.
    """
    global FAIL_COUNT

    if not GOLDEN_AVAILABLE:
        dut._log.info("[SKIP] test_internal_signals: golden_model.py not available")
        return

    await ensure_clock(dut)
    await reset_dut(dut)

    expected_cycles = golden_run()
    if not expected_cycles:
        dut._log.info("[SKIP] test_internal_signals: golden model returned no data")
        return

    # Check if trace includes internal signals (any key containing '.' or ending with _reg)
    has_internal = any('.' in k or k.endswith('_reg')
                       for entry in expected_cycles for k in entry.keys())
    if not has_internal:
        dut._log.info("[SKIP] test_internal_signals: golden trace has no internal signals")
        return

    dut._log.info(f"[INTERNAL] Comparing {len(expected_cycles)} cycles, internal signals")

    # IMPORTANT: codegen MUST add drive_inputs() call here with golden model
    # test vectors before the comparison loop. Without driving inputs,
    # the DUT has no stimulus and all outputs will be initial values.
    # <CODEGEN: drive_inputs() call here — same as test_layered>

    # Stimulus tracking: drive_inputs() may have cleared data inputs by the
    # time we reach this point (intentional, end-of-hold deassert), so we
    # cannot decide "was stimulus driven?" from a single snapshot here.
    # Instead we sample input ports inside the comparison loop and raise if
    # NONE were ever non-zero across the full comparison window.
    _stimulus_seen_nonzero = False

    first_divergence = None
    cycles_checked = 0
    signals_compared = 0
    signals_not_found = []

    # Alignment derivation — see the matching block in test_layered for the
    # full rationale. drive_inputs() already consumed DRIVE_PHASE_CYCLES inside
    # itself. The slice here only skips golden cycle 0 (reset state), and we
    # compare BEFORE the await so iteration 0 sees the DUT state left by
    # drive_inputs (= golden cycle 1).
    compare_cycles = expected_cycles[RESET_CYCLE_SKIP:]

    for cycle_idx, expected in enumerate(compare_cycles):
        # Track stimulus: read every input port even when golden trace omits
        # it, so a missing drive_inputs() is detected via the post-loop check.
        for in_name in INPUT_PORTS:
            try:
                if int(getattr(dut, in_name).value) != 0:
                    _stimulus_seen_nonzero = True
                    break
            except (AttributeError, ValueError):
                pass

        for sig_name, expected_val in expected.items():
            if sig_name in INPUT_PORTS:
                # Stimulus comparison: golden trace recorded the input value
                # the DUT is expected to see this cycle. If RTL input doesn't
                # match, the testbench driver is wrong (not the DUT).
                try:
                    actual_val = int(getattr(dut, sig_name).value)
                    signals_compared += 1
                    if actual_val != expected_val:
                        first_divergence = {
                            "cycle": cycle_idx,
                            "signal": sig_name,
                            "expected": expected_val,
                            "actual": actual_val,
                            "kind": "stimulus_mismatch",
                        }
                        break
                except (AttributeError, ValueError):
                    pass
                continue

            try:
                # Navigate VPI hierarchy for module-qualified names
                if '.' in sig_name:
                    parts = sig_name.split('.')
                    obj = dut
                    for part in parts:
                        # Handle array indexing: w_reg[0] → w_reg, index 0
                        if '[' in part:
                            arr_name, idx_str = part.split('[')
                            idx = int(idx_str.rstrip(']'))
                            obj = getattr(obj, arr_name)
                            obj = obj[idx]
                        else:
                            obj = getattr(obj, part)
                    actual_val = int(obj.value)
                else:
                    sig = getattr(dut, sig_name)
                    actual_val = int(sig.value)

                signals_compared += 1
                if actual_val != expected_val:
                    first_divergence = {
                        "cycle": cycle_idx,
                        "signal": sig_name,
                        "expected": expected_val,
                        "actual": actual_val,
                    }
                    break
            except (AttributeError, IndexError):
                if sig_name not in signals_not_found:
                    signals_not_found.append(sig_name)

        cycles_checked += 1
        if first_divergence:
            break

        # Advance DUT one cycle for the NEXT golden entry.
        await RisingEdge(dut.clk)

    # Stimulus sanity check: if INPUT_PORTS is non-empty but no input ever
    # went non-zero across the entire comparison window, drive_inputs() was
    # almost certainly never called (or called with all-zero values).
    if INPUT_PORTS and not _stimulus_seen_nonzero:
        raise AssertionError(
            "test_internal_signals: no input stimulus observed across "
            f"{cycles_checked} cycle(s) — drive_inputs() may have been "
            "skipped or called with all-zero values"
        )

    # Warn about signals that could not be found in DUT hierarchy
    if signals_not_found:
        dut._log.warning(
            f"[INTERNAL] {len(signals_not_found)} signal(s) not found in DUT, "
            f"skipped: {signals_not_found[:5]}"
            + (f" ... and {len(signals_not_found)-5} more" if len(signals_not_found) > 5 else "")
        )

    # Safety check: verify we actually compared something
    if signals_compared == 0:
        dut._log.error(
            "[INTERNAL] ZERO signals were compared — golden trace signal names "
            "do not match any DUT signals. Check naming convention."
        )
        raise AssertionError(
            "test_internal_signals: no signals compared, trace names may not match RTL"
        )

    if first_divergence:
        FAIL_COUNT += 1
        div = first_divergence
        kind = div.get("kind", "signal_mismatch")
        kind_tag = " kind=stimulus_mismatch" if kind == "stimulus_mismatch" else ""
        hint = (
            "  (testbench driver wrong — DUT input doesn't match golden stimulus)"
            if kind == "stimulus_mismatch" else ""
        )
        msg = (
            f"[INTERNAL] FIRST DIVERGENCE at cycle={div['cycle']} "
            f"signal={div['signal']}{kind_tag}: "
            f"expected=0x{div['expected']:08x} got=0x{div['actual']:08x}"
            f"{hint}"
        )
        dut._log.error(msg)
        raise AssertionError(msg)
    else:
        dut._log.info(
            f"[INTERNAL] PASS — {cycles_checked} cycles, "
            f"{signals_compared} signal values matched"
        )


@cocotb.test()
async def test_summary(dut):
    """Final test: reports overall pass/fail."""
    global FAIL_COUNT
    await ensure_clock(dut)
    await RisingEdge(dut.clk)
    if FAIL_COUNT == 0:
        dut._log.info("ALL TESTS PASSED")
    else:
        dut._log.error(f"FAILED: {FAIL_COUNT} assertion(s) failed")
